// Expo config plugin: make NOVIA's alarm ring as a real full-screen screen.
//
// Notifee's `fullScreenAction` launches MainActivity when the alarm fires, but
// Android will only show that activity OVER the lock screen (and turn the screen
// on) if the activity itself declares `showWhenLocked` + `turnScreenOn`. Without
// these, the OS silently demotes the alarm to a plain heads-up notification.
//
// The android/ folder is generated by `expo prebuild`, so this can't live in a
// hand-edited manifest — it has to be injected here on every build.
const { withAndroidManifest } = require('@expo/config-plugins');

module.exports = function withAlarmFullScreen(config) {
  return withAndroidManifest(config, (cfg) => {
    const application = cfg.modResults.manifest.application?.[0];
    if (!application) return cfg;

    const mainActivity = (application.activity || []).find(
      (a) => a?.$?.['android:name'] === '.MainActivity',
    );
    if (!mainActivity) return cfg;

    // Appear over the keyguard and wake the display when the alarm fires.
    mainActivity.$['android:showWhenLocked'] = 'true';
    mainActivity.$['android:turnScreenOn'] = 'true';

    return cfg;
  });
};
